/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;

namespace DefaultNamespace
{
    public class TypeTestTableUpdate : TypedRecordUpdate<Tuple<TypeTestTable?, TypeTestTable?>> { }

    public class TypeTestTable : IMudTable
    {
        public static readonly TableId TableId = new("", "TypeTest");

        public byte? value;

        public static TypeTestTable? GetTableValue(string key)
        {
            var query = new Query()
                .Find("?value", "?attribute")
                .Where(TableId.ToString(), key, "?attribute", "?value");
            var result = NetworkManager.Instance.ds.Query(query);
            var typeTestTable = new TypeTestTable();
            var hasValues = false;

            foreach (var record in result)
            {
                var attribute = record["attribute"].ToString();
                var value = record["value"];

                switch (attribute)
                {
                    case "value":
                        var valueValue = (byte)value;
                        typeTestTable.value = valueValue;
                        hasValues = true;
                        break;
                }
            }

            return hasValues ? typeTestTable : null;
        }

        public static IObservable<TypeTestTableUpdate> OnRecordUpdate()
        {
            return NetworkManager.Instance.ds.OnDataStoreUpdate
                .Where(
                    update =>
                        update.TableId == TableId.ToString() && update.Type == UpdateType.SetField
                )
                .Select(
                    update =>
                        new TypeTestTableUpdate
                        {
                            TableId = update.TableId,
                            Key = update.Key,
                            Value = update.Value,
                            TypedValue = MapUpdates(update.Value)
                        }
                );
        }

        public static IObservable<TypeTestTableUpdate> OnRecordInsert()
        {
            return NetworkManager.Instance.ds.OnDataStoreUpdate
                .Where(
                    update =>
                        update.TableId == TableId.ToString() && update.Type == UpdateType.SetRecord
                )
                .Select(
                    update =>
                        new TypeTestTableUpdate
                        {
                            TableId = update.TableId,
                            Key = update.Key,
                            Value = update.Value,
                            TypedValue = MapUpdates(update.Value)
                        }
                );
        }

        public static IObservable<TypeTestTableUpdate> OnRecordDelete()
        {
            return NetworkManager.Instance.ds.OnDataStoreUpdate
                .Where(
                    update =>
                        update.TableId == TableId.ToString()
                        && update.Type == UpdateType.DeleteRecord
                )
                .Select(
                    update =>
                        new TypeTestTableUpdate
                        {
                            TableId = update.TableId,
                            Key = update.Key,
                            Value = update.Value,
                            TypedValue = MapUpdates(update.Value)
                        }
                );
        }

        public static Tuple<TypeTestTable?, TypeTestTable?> MapUpdates(
            Tuple<Property?, Property?> value
        )
        {
            TypeTestTable? current = null;
            TypeTestTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new TypeTestTable
                    {
                        value = value.Item1.TryGetValue("value", out var valueVal)
                            ? (byte)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new TypeTestTable { value = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new TypeTestTable
                    {
                        value = value.Item2.TryGetValue("value", out var valueVal)
                            ? (byte)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new TypeTestTable { value = null, };
                }
            }

            return new Tuple<TypeTestTable?, TypeTestTable?>(current, previous);
        }
    }
}
