/* Autogenerated file. Manual edits will not be saved.*/

#nullable enable
using System;
using mud.Client;
using mud.Network.schemas;
using mud.Unity;
using UniRx;
using Property = System.Collections.Generic.Dictionary<string, object>;
using System.Collections.Generic;
using UnityEngine;

namespace DefaultNamespace
{
    public class TypeTestTableUpdate : TypedRecordUpdate<Tuple<TypeTestTable?, TypeTestTable?>> { }

    public class TypeTestTable : IMudTable
    {
        public readonly static TableId ID = new("", "TypeTest");

        public override TableId GetTableId()
        {
            return ID;
        }

        public byte? value;

        public override Type TableType()
        {
            return typeof(TypeTestTable);
        }

        public override Type TableUpdateType()
        {
            return typeof(TypeTestTableUpdate);
        }

        public override void SetValues(params object[] functionParameters)
        {
            value = (byte)functionParameters[0];
        }

        public override bool SetValues(IEnumerable<Property> result)
        {
            var hasValues = false;
            foreach (var record in result)
            {
                var attribute = record["attribute"].ToString();
                var value = record["value"];

                switch (attribute)
                {
                    case "value":
                        var valueValue = (byte)value;
                        value = valueValue;
                        hasValues = true;
                        break;
                }
            }

            return hasValues;
        }

        public override IMudTable GetTableValue(string key)
        {
            var query = new Query()
                .Find("?value", "?attribute")
                .Where(TableId.ToString(), key, "?attribute", "?value");
            var result = NetworkManager.Instance.ds.Query(query);
            var typeTestTable = new TypeTestTable();
            var hasValues = false;

            foreach (var record in result)
            {
                var attribute = record["attribute"].ToString();
                var value = record["value"];

                switch (attribute)
                {
                    case "value":
                        var valueValue = (byte)value;
                        typeTestTable.value = valueValue;
                        hasValues = true;
                        break;
                }
            }

            return hasValues ? typeTestTable : null;
        }

        public override IMudTable RecordUpdateToTable(RecordUpdate tableUpdate)
        {
            TypeTestTableUpdate update = (TypeTestTableUpdate)tableUpdate;

            var currentValue = update?.TypedValue.Item1;
            if (currentValue == null)
            {
                Debug.LogError("No value on TypeTestTable update");
            }

            return currentValue;
        }

        public override RecordUpdate CreateTypedRecord(RecordUpdate newUpdate)
        {
            return new TypeTestTableUpdate
            {
                TableId = newUpdate.TableId,
                Key = newUpdate.Key,
                Value = newUpdate.Value,
                TypedValue = MapUpdates(newUpdate.Value)
            };
        }

        public static Tuple<TypeTestTable?, TypeTestTable?> MapUpdates(
            Tuple<Property?, Property?> value
        )
        {
            TypeTestTable? current = null;
            TypeTestTable? previous = null;

            if (value.Item1 != null)
            {
                try
                {
                    current = new TypeTestTable
                    {
                        value = value.Item1.TryGetValue("value", out var valueVal)
                            ? (byte)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    current = new TypeTestTable { value = null, };
                }
            }

            if (value.Item2 != null)
            {
                try
                {
                    previous = new TypeTestTable
                    {
                        value = value.Item2.TryGetValue("value", out var valueVal)
                            ? (byte)valueVal
                            : default,
                    };
                }
                catch (InvalidCastException)
                {
                    previous = new TypeTestTable { value = null, };
                }
            }

            return new Tuple<TypeTestTable?, TypeTestTable?>(current, previous);
        }
    }
}
